name: Dry Run

on:
  # Runs on pushes targeting the default branch
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup